In [60]:
import tensorflow as tf

### this is constant declaration while we know the inputs

In [17]:
# constant Declaration 
x= tf.constant([4],tf.int32)  # here we already declare constant value with its type
y= tf.constant([78,28,49])

c = tf.multiply(x,y) # this is our operation

In [18]:
with tf.Session() as s :      # this is 1 method session will start and close automatically with loop execute
    op=s.run(c)
    print(op)

[312 112 196]


In [20]:
s = tf.Session()     # this is another way to start session
a =s.run(c)
print(a)
s.close()     # this we need to close to stop the further operation.

[312 112 196]


### this is placeholder declaration while we dont know the inputs

In [21]:
# sometimes such situation like we only know the input type but we dont know the acutal input .
# to handle this kind of opearation we just generally define the data type only.

In [72]:
x= tf.placeholder(tf.int32)
y= tf.placeholder(tf.int32)

c = tf.add(x,y)

with tf.Session() as s:
    op = s.run(c,{x:[1,4,2],y:[5,3,7]}) # here we are feeding our x,y values at run time.
    print(op)
    

[6 7 9]


### this is Variable declaration. it useful  while we  perform the operation it  will change its values

In [73]:
# Variable is bascially define with the initial values but we want to manipulate it while performing the opeartions.
# in this kind of situation Variable  are vary useful. it allows to modify or change the initial values

In [74]:
x= tf.Variable([37,42,48])
y= tf.Variable([37,7,24])
c= x/y
init= tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
print(sess.run(c))
# with tf.Session() as sess:
#     sess.run(init)
#     result = sess.run(c)
#     print(result)


[1. 6. 2.]


In [75]:
a = tf.constant([47.2,434.4])
b = tf.constant([89.1])
x= a*b
sess= tf.Session()
print(sess.run(x))
sess.close()

[ 4205.52 38705.04]


###  Linear Regression Bigginers Steps

In [89]:
# Y = b + w*x
w = tf.Variable([.5], tf.float32)
b = tf.Variable([.4], tf.float32)
x = tf.placeholder(tf.float32)

model = w*x + b

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(model,{x:[54,89,23,34]}))
    

[27.4 44.9 11.9 17.4]


### Activation Functions [ important]
#### 1. Liner   ==>  f(x) =x     same value return from the function
#### 2. Unit Step   ==>  f(x) = { if x> 5 : 0 else 1}  this is something like  threshould (condition) here 5 is threshould
#### 3. Sigmoid   ==>  f(x) = {1/ 1+e ^bx} this function returns values between 0 to 1
#### 4. Tanh   ==>  f(x) = tanh(x)   this function returns values between -1 to 1
#### 5. Relu   ==>  f(x) = { if x>0 : x else 0} it means negative values become 0 and positive is same
#### 6. Softmax   ==>  f(x)  this func. is  useful to finding the the maximum probability


### Loss Function
#### this function will helpful while we need to calcualte the total loss during the operation.

In [124]:
### this is normal regural linear model 
import tensorflow as tf
W = tf.constant([.3],tf.float32)
b = tf.constant([-.3],tf.float32)
x = tf.placeholder(tf.float32)
x = tf.placeholder(tf.float32)
linear_model = W * x + b

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(linear_model,{x:[1,2,3,4]}))
    

[0.         0.3        0.6        0.90000004]


In [126]:
### this is extended to calculate the lost/cost function in linear_model operation.
import tensorflow as tf
W = tf.Variable([.3],tf.float32)
b = tf.Variable([-.3],tf.float32) 
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
linear_model = W * x + b
sigmoid_fun = tf.square(linear_model - y)        # here we are squaring the sigmoid
loss = tf.reduce_sum(sigmoid_fun)     # we apply to optimize the sum for reducing loss

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(loss,{x:[1,2,3,4],y:[0,1,1,3]}))  # here we applied our variables on loss function.
    ## here its sum all the loss and print o/p

5.0599995


### Model Optimizer

In [105]:
# steps to perform
# 1. Normal construst the model(Function) Here {liner function we are using for batter understanding}
# 2. Apply loss/cost function on our model(linear function) it..!! same like above we dont 
# 3. Then apply optimization function  on the {loss} function..!! to get optimal results

In [151]:
import tensorflow as tf
W = tf.Variable([.1],tf.float32)
b = tf.Variable([.3],tf.float32)
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

linear_model = W * x + b

_SigmoidFun = tf.square(linear_model - y)
loss = tf.reduce_sum(_SigmoidFun)

# lets add optimizer on loss
optimizer = tf.train.GradientDescentOptimizer(0.01)
# optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(loss)

train = optimizer.minimize(loss)

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    for i in range(3):
        print(sess.run(train,{x:[3,1,4,8],y:[0.,1,2,3]}))


None
None
None


In [168]:
### this is extended to calculate the lost/cost function in linear_model operation.
import tensorflow as tf
W = tf.Variable([.3],tf.float32)
b = tf.Variable([-.3],tf.float32) 
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
linear_model = W * x + b
sigmoid_fun = tf.square(linear_model - y) 
# here we are squaring the sigmoid
loss = tf.reduce_sum(sigmoid_fun)     # we apply to optimize the sum for reducing loss
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(loss)

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    for i in range(3):
        print(optimizer)

#         print(sess.run(sigmoid_fun,{x:[1,2,3,4],y:[0,1,1,3]}))  # here we applied our variables on loss function.
    ## here its sum all the loss and print o/p

name: "GradientDescent_47"
op: "NoOp"
input: "^GradientDescent_47/update_Variable_194/ApplyGradientDescent"
input: "^GradientDescent_47/update_Variable_195/ApplyGradientDescent"

name: "GradientDescent_47"
op: "NoOp"
input: "^GradientDescent_47/update_Variable_194/ApplyGradientDescent"
input: "^GradientDescent_47/update_Variable_195/ApplyGradientDescent"

name: "GradientDescent_47"
op: "NoOp"
input: "^GradientDescent_47/update_Variable_194/ApplyGradientDescent"
input: "^GradientDescent_47/update_Variable_195/ApplyGradientDescent"

