### <center>Numpy basics and Sciket-learn</center>

In [135]:
# this NN only based on numpy we are not using any other library to implment NN.
import numpy as np

In [16]:
np.random.seed(3)

In [108]:
np.random.randint(0,100,10)

array([21, 38, 96, 20, 44, 93, 39, 14, 26, 81])

In [109]:
np.random.seed(3)

In [110]:
np.random.randint(0,100,10)

array([24,  3, 56, 72,  0, 21, 19, 74, 41, 10])

In [119]:
x=1
1 / (1 + np.exp(-x))

0.7310585786300049

In [151]:
a=[[1,2],[3,4]]
b=[[11,12],[13,14]]
np.dot(a,b)


ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [161]:
import tensorflow as tf
from sklearn import preprocessing


In [142]:
a=tf.matmul(a,b)

In [163]:
input_data = np.array([[3, -1.5, 3, -6.4], [0, 3, -1.3, 4.1], [1, 2.3, -2.9, -4.3]])
data_standardized = preprocessing.scale(input_data)
data_standardized

array([[ 1.33630621, -1.39936232,  1.36473933, -0.9258201 ],
       [-1.06904497,  0.87670892, -0.36125453,  1.38873015],
       [-0.26726124,  0.5226534 , -1.0034848 , -0.46291005]])

In [164]:
print("\nMean = ", data_standardized.mean(axis = 0))
print("Std deviation = ", data_standardized.std(axis = 0))


Mean =  [ 5.55111512e-17 -3.70074342e-17  0.00000000e+00 -1.85037171e-17]
Std deviation =  [1. 1. 1. 1.]


In [168]:
data_scaler = preprocessing.MinMaxScaler(feature_range = (0, 1))

data_scaled = data_scaler.fit_transform(input_data)
data_scaled
# print("\nMin max scaled data =\n ", data_scaled)

array([[1.        , 0.        , 1.        , 0.        ],
       [0.        , 1.        , 0.27118644, 1.        ],
       [0.33333333, 0.84444444, 0.        , 0.2       ]])

In [173]:
1.3/2**4


0.08125