# <center>Numpy Arithmatic Operations</center>

### array with array,
### array with scalar,
### array with universal functions

In [1]:
import numpy as np

In [2]:
array = np.arange(1,11)

In [3]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
array + array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
array - array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
array * array

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [9]:
array **7

array([       1,      128,     2187,    16384,    78125,   279936,
         823543,  2097152,  4782969, 10000000], dtype=int32)

In [10]:
array/array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
array%array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [17]:
10/array

array([10.        ,  5.        ,  3.33333333,  2.5       ,  2.        ,
        1.66666667,  1.42857143,  1.25      ,  1.11111111,  1.        ])

### Univeral Functions

In [13]:
np.exp(array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [14]:
np.log(array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [15]:
np.sin(array)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [16]:
np.sqrt(array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [18]:
np.max(array)

10

### take a look for more Universal functions https://docs.scipy.org/doc/numpy-1.16.1/reference/ufuncs.html

### i thought in this no need to explain all the function and output is enough to understand at first look.
### if you still have some difficulties you may comment down below.