# <center>Numpy Indexing & Selection</center>

In [1]:
import numpy as np

In [2]:
l =['f','s','t','f','ff','six','s7','s8','s9','s10']  #normal list

In [8]:
l[3:]

['f', 'ff', 'six', 's7', 's8', 's9', 's10']

In [9]:
arr= np.array(l)  #list to array convesion 
arr

array(['f', 's', 't', 'f', 'ff', 'six', 's7', 's8', 's9', 's10'],
      dtype='<U3')

In [11]:
arr[3:]      # all the operation you can perform as list to array also.!!

array(['f', 'ff', 'six', 's7', 's8', 's9', 's10'], dtype='<U3')

###  brodcasting ,copying and shallow copying

In [12]:
arr

array(['f', 's', 't', 'f', 'ff', 'six', 's7', 's8', 's9', 's10'],
      dtype='<U3')

In [14]:
arr[0:3]

array(['f', 's', 't'], dtype='<U3')

In [17]:
arr[0:3] =99   # this will brodcast the selected index with the value 99. inshort assign value 99 to selected array.

In [16]:
arr       # it will change the original array. 

array(['99', '99', '99', 'f', 'ff', 'six', 's7', 's8', 's9', 's10'],
      dtype='<U3')

### if you dont want to change the original array value you van copy the main array to another then perform the opration.

In [22]:
original_arr = arr

In [23]:
original_arr            # over main array

array(['99', '99', '99', 'f', 'ff', 'six', 's7', 's8', 's9', 's10'],
      dtype='<U3')

In [25]:
copy_arr = original_arr.copy()  # copy original array to another array 

In [26]:
copy_arr

array(['99', '99', '99', 'f', 'ff', 'six', 's7', 's8', 's9', 's10'],
      dtype='<U3')

In [27]:
copy_arr[:]=100       # change the value of copy_arr as 100

In [28]:
copy_arr    # array values are change to 100.

array(['100', '100', '100', '100', '100', '100', '100', '100', '100',
       '100'], dtype='<U3')

In [29]:
original_arr   # but here it didnt affact the original array.

array(['99', '99', '99', 'f', 'ff', 'six', 's7', 's8', 's9', 's10'],
      dtype='<U3')

### Multi-Dimension array Selection / grabbing values 

In [30]:
arr2D = np.array([[0,5,10],[15,20,25],[30,35,40],[45,50,55]])   # 2-D array created

In [31]:
arr2D       # over 2-D array

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40],
       [45, 50, 55]])

In [32]:
# fetch/greab values using [][] or [,]  

In [65]:
arr2D[1]            # this will fetch whole row of given number.

array([15, 20, 25])

In [39]:
arr2D[1,2]           # this is standerd way / less possiblity of errors, here index no of [row,column] 

25

In [34]:
arr2D[1][1]           # this is regular way / possiblity of doing errors is high , here index no of [row][column]

20

In [36]:
# you can try to grabe any value of the array using standerd way, or else you can prefer any of them.
# easy and batter way is the standerd way.

In [51]:
arr2D       # over 2-D array

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40],
       [45, 50, 55]])

In [63]:
# lets grabbing matrix
arr2D[:2,:2]
# here row = [0:2] it means first two rows
# and coulmns [0:2] it means first two columns
# you can try to grab matrix, rows, columns. check out  this examples arr2D[2:,1:] ,arr2D[:,2:] and see the result.

array([[ 0,  5],
       [15, 20]])

### conditional fetching the values

In [146]:
arr = np.random.randint(1,500,50).reshape(5,10)   # 2-D array creatation with randome values between 1-499 size of 50 

In [173]:
arr                              # original array

array([[126, 288, 127, 136, 496,  48,  38, 252, 469, 159],
       [359, 435, 301, 125,  25, 441, 347, 207, 179, 134],
       [ 54, 226, 416,  17, 382,  68, 302, 400, 147, 306],
       [128, 372, 401, 398,  58, 294, 450,  48, 133,  68],
       [145, 258, 136, 450, 413,  42, 211,  51,  48, 309]])

In [126]:
boolean_array = arr>100         # our condition values must be greater then 100.
boolean_array                   # it gives boolean array where value is greater then 100 it gives true else false.

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True],
       [False, False,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True, False,  True,  True, False,  True,
         True]])

In [127]:
arr[boolean_array]              # boolean array pass to original array to get values greater then 100.

array([461, 237, 469, 328, 187, 422, 226, 143, 149, 432, 294, 103, 478,
       405, 344, 286, 327, 180, 114, 135, 354, 334, 418, 150, 163, 244,
       332, 385, 401, 451, 147, 460, 210, 486, 199, 385, 191, 397, 494,
       388, 269, 370, 495, 337, 387])

In [ ]:
# this is the shortcut to get values directly from the array

In [128]:
arr[arr>100]       #conditional fetching all the values are greater 100 will store in m100.

array([461, 237, 469, 328, 187, 422, 226, 143, 149, 432, 294, 103, 478,
       405, 344, 286, 327, 180, 114, 135, 354, 334, 418, 150, 163, 244,
       332, 385, 401, 451, 147, 460, 210, 486, 199, 385, 191, 397, 494,
       388, 269, 370, 495, 337, 387])

### try to print diagonal values orginal and rest of values fill with dummy value as 99 or anyother.

In [208]:
arr1 = arr.copy()  #lets copy org. array to tempararoy array

In [209]:
temp=list()       # temp. list to store the diagonal value

In [210]:
for v,i in enumerate(arr):
    print(v,i)
    temp.append(arr[v][v])    # store the diagonal values to list
    arr1[v]=99                # in row fill all the values with dummy
    arr1[v][v]=temp[v]        # fill the diagonal value in the perticular place in row
    
#     print(arr1[i][i])
#     a= arr1[v]
#     arr1
#     print(arr1.index(a))
# #     a[i+1:] = 99
#     temp.append(a)

0 [126 288 127 136 496  48  38 252 469 159]
1 [359 435 301 125  25 441 347 207 179 134]
2 [ 54 226 416  17 382  68 302 400 147 306]
3 [128 372 401 398  58 294 450  48 133  68]
4 [145 258 136 450 413  42 211  51  48 309]


In [211]:
temp

[126, 435, 416, 398, 413]

In [212]:
arr1

array([[126,  99,  99,  99,  99,  99,  99,  99,  99,  99],
       [ 99, 435,  99,  99,  99,  99,  99,  99,  99,  99],
       [ 99,  99, 416,  99,  99,  99,  99,  99,  99,  99],
       [ 99,  99,  99, 398,  99,  99,  99,  99,  99,  99],
       [ 99,  99,  99,  99, 413,  99,  99,  99,  99,  99]])

### now your task to fil the diagonal values from the top right to left and rest of fill with dummy value as 99


In [ ]:
# output as below:
#     [[126,  99,  99,  99,  99,  99,  99,  99,  99,  159],
#      [99,  435,  99,  99,  99,  99,  99,  99,  179,  99],
#      [ 99,  99,  435,  99,  99,  99,  99,  400,  99,  99],
#      [99,  99,  99,  435,  99,  99,  450,  99,  99,  99],
#      [99,  99,  99,  99,  413,  42,  99,  99,  99,  99]]