# <center>Numpy Basics</center>

### Array conversion from the list, Creation, info of Array

In [4]:
import numpy  as np

In [15]:
seq =['second', 'first', 'last', 's']

In [16]:
arr = np.array(seq)     # list convert to array

In [17]:
arr

array(['second', 'first', 'last', 's'], dtype='<U6')

In [82]:
arr = np.arange(1,10)     # create 1-D array 

In [83]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr.shape   # this will show the dimension of the array, here 1-D only row value, if no column value that mean 1-D

(9,)

In [79]:
arr.dtype    # to check the data type of the array.

dtype('int32')

### 2-D array conversion from nested list

In [64]:
arr               # values in array "arr"

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
arr = arr.reshape(3,3)      # conversion of 1-D to 2-D array by giving reshape().

In [73]:
arr                     

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
 arr.shape   # to check the dimension of the array, here 2-D no of rows is 3 and columns also 3

(3, 3)

In [47]:
l = [[1,2,3],[4,5,6],[7,8,9]]   # nested list

In [51]:
np.array(l)        # nested list to array conversion this is 2-D array. you just count the bracates "[[...]]" to know it.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
np.arange(1,10,4)  # third argument it will shows that stps it will jump here 0 then 4 steps [1,2,3,4]

array([1, 5, 9])

In [13]:
np.linspace(0,10,5)      # this will divide 5 part from 0 to 10, here 5 is no of parts we want to divide. [0,10] is range.

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [27]:
np.zeros((2,3))            # it will fill the zeros according to given rows and columns here 2 rows and 3 columns

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.ones((3,4))            # it will fill the once according to given rows and columns here 3 rows and 4 columns

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### identity matrix (diagonal values represent with 0's or 1's)

In [60]:
np.eye(5)        # here, 1's shows that it will be diagonal(identity) matrix. and rest of the values are 0's

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### playing with random numbers and its function with np

In [29]:
np.random.rand(5)  # this is 1-D array with value in between 0-1

array([0.1071854 , 0.32665146, 0.89477413, 0.00378239, 0.46584332])

In [30]:
np.random.rand(5,5)  # this is 2-D array with value in between 0-1 fill 5 rows and 5 columns

array([[0.54979773, 0.03964151, 0.86451245, 0.76644186, 0.20824185],
       [0.71952884, 0.47996681, 0.67317484, 0.30641464, 0.27028107],
       [0.06567254, 0.4970889 , 0.04851953, 0.27970184, 0.48269363],
       [0.40544442, 0.16955463, 0.49732229, 0.41076465, 0.07155184],
       [0.41732747, 0.82575386, 0.82743095, 0.24128962, 0.13181806]])

In [31]:
np.random.randn(10)   # this will give random 1-D array number near by 0. but values can be + and -  randomly.

array([ 0.55103674,  0.8475879 ,  0.19158052, -0.5060677 , -0.17261326,
       -1.92595387, -0.1325583 , -1.18349035, -0.16593728,  1.63079571])

In [32]:
np.random.randn(2,5)   # this will give random 2-D array number near by 0. but values can be + and -  randomly.

array([[ 1.82568318,  1.40735846, -1.16821254,  0.33232354,  0.72300633],
       [-0.93843054, -0.98318058,  0.79954708,  0.01487986,  0.21603097]])

In [43]:
np.random.randint(1,100)   # this give any randome value from the given range. here [1-99]

62

In [40]:
np.random.randint(1,100,10)   # this give any 10 randome value from the given range. here [1-99]

array([66, 79, 71, 97, 56, 96, 62, 80, 87,  8])

In [44]:
randarray = np.random.randint(0,100,10)   # array created with 10 random values and values between [1-99]

In [45]:
randarray

array([17, 45, 71, 87, 20, 82, 89,  4, 65, 70])

In [60]:
print("From Array: max Value=> {}, min Value=> {}".format(randarray.max(), randarray.min()))

From Array: max Value=> 89, min Value=> 4


In [61]:
print("From Array: Index of max=> {}, Index of min=> {}".format(randarray.argmax(), randarray.argmin()))

From Array: Index of max=> 6, Index of min=> 7
